### ISSUE TITLE
visualize not working when remotely accessing notebook

### ISSUE THREAD

**Issue by drpventura** [CurricularAnalytics/CurricularAnalytics.jl#87]
I am trying to determine if `visualize` only works through Jupyter when you are using a browser from the local machine.

I am trying to setup an instance in Google Cloud of CourseAnalytics with Julia and Jupyter running.  However, whenever I try to run the visualize command it spins for a while and then produces a gray box saying "localhost refused to connect" (see screenshot below).
<img width="908" alt="no-viz" src="https://user-images.githubusercontent.com/737066/74481648-2105d700-4e81-11ea-9300-6cb05d9009db.png">

I also tried setting up in an Ubuntu guest in VirtualBox.  When I try to connect from within the Ubuntu instance (to itself) `visualize` works.  However, when I try to connect to the Ubuntu (host) server from my Windows (guest), I get the same message as above about not being able to connect.  Is this by design or is it an error?  Note: I have run `using WebIO` and ``WebIO.install_jupyter_nbextension()` before running notebook.

**Comment by haydenfree** [comment]
Hi Dr. Ventura, we've been working to make the Jupyter Notebook experience more reliable but I don't think we've come across this bug before. I've previously set up Jupyter running on an Amazon EC2 instance and visualized plans without problem, but it's possible something has broken since then.

Jiacheng has been focused on the Jupyter side of things so I am going to include him on this issue.

@jiachengzhang1 Have you run into this issue? Any ideas on what may be causing it?

**Comment by jiachengzhang1** [comment]
Yeah, this is because there's no a server set up to render the embedded visualization html page to notebook when using ec2

you could resolve it by setting the https://github.com/CurricularAnalytics/CurricularAnalytics.jl/blob/b90412c03d7e9e082adee01c5e8e7ef3fdfe85ad/src/Visualization.jl#L15 
to the src url from the template. https://github.com/CurricularAnalytics/CurricularAnalytics.jl/blob/b90412c03d7e9e082adee01c5e8e7ef3fdfe85ad/src/visualization-template.html#L19

**Comment by drpventura** [comment]
That fixed it.  Thanks!
